server:
    port: 7001
spring:
    application:
         name: SSOAuth
    #redis
    redis:
      host: 127.0.0.1
      port: 6379
      #password: yinhetianze
      timeout: 60000
      pool.max-idle: 100
      pool.max-active: 200
